# Generated by Django 4.2.5 on 2023-09-30 15:16

from django.db import migrations, models
import django.db.models.deletion
import test_django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('name', models.CharField(help_text='Введите название направления', max_length=150, primary_key=True, serialize=False, verbose_name='name division')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите номер курса', max_length=20, verbose_name='name group')),
                ('course', test_django.models.IntegerRangeField(help_text='Введите номер курса', verbose_name='name course')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50, verbose_name='name')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='last name')),
                ('divisions', models.ForeignKey(help_text='Выберите направление', on_delete=django.db.models.deletion.CASCADE, to='test_django.divisions', verbose_name='name diivision')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Введите имя', max_length=50, null=True, verbose_name='name')),
                ('last_name', models.CharField(help_text='Введите имя', max_length=100, verbose_name='last name')),
                ('date_birth', models.DateField(help_text='Введите дату рождения', verbose_name='date birth')),
                ('group', models.ForeignKey(help_text='Введите курс', on_delete=django.db.models.deletion.CASCADE, to='test_django.group', verbose_name='id course')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', test_django.models.IntegerRangeField(help_text='Введите оценку за лабу от 0 до 7', verbose_name='lab mark')),
                ('date_control', models.DateField(help_text='Введите дату сдачи', verbose_name='date control')),
                ('student', models.ForeignKey(help_text='Выберите студента', on_delete=django.db.models.deletion.CASCADE, to='test_django.student', verbose_name='student')),
                ('tutor', models.ForeignKey(help_text='Выберите проверяющего педагога', on_delete=django.db.models.deletion.CASCADE, to='test_django.tutor', verbose_name='name')),
            ],
        ),
    ]
