# Generated by Django 4.2.5 on 2023-09-30 15:46

from django.db import migrations, models
import django.db.models.deletion
import test_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Введите номер отдела', max_length=20, verbose_name='Номер отдела')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('name', models.CharField(help_text='Введите название направления', max_length=150, primary_key=True, serialize=False, verbose_name='Название направления')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Введите имя', max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите имя', max_length=100, verbose_name='Фамилия')),
                ('date_birth', models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения')),
                ('department', models.ForeignKey(help_text='Введите отдел', on_delete=django.db.models.deletion.CASCADE, to='test_django.department', verbose_name='id отдела')),
            ],
        ),
        migrations.CreateModel(
            name='Reform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', test_django.models.IntegerRangeField(help_text='Введите сумму бюджета', verbose_name='Бюджет')),
                ('deadline', models.DateField(help_text='Введите дату сдачи', verbose_name='Сроки')),
                ('boss', models.ForeignKey(help_text='Выберите уполномоченного начальника', on_delete=django.db.models.deletion.CASCADE, to='test_django.boss', verbose_name='Имя')),
                ('minister', models.ForeignKey(help_text='Выберите министра', on_delete=django.db.models.deletion.CASCADE, to='test_django.minister', verbose_name='Министр')),
            ],
        ),
        migrations.RemoveField(
            model_name='lab',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='divisions',
        ),
        migrations.DeleteModel(
            name='Divisions',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.AddField(
            model_name='boss',
            name='direction',
            field=models.ForeignKey(help_text='Выберите направление', on_delete=django.db.models.deletion.CASCADE, to='test_django.direction', verbose_name='Название направления'),
        ),
    ]
