# Generated by Django 4.2.5 on 2023-09-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0002_boss_department_direction_minister_reform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reform',
            name='boss',
            field=models.ForeignKey(help_text='Выберите уполномоченного начальника', on_delete=django.db.models.deletion.CASCADE, to='test_django.boss', verbose_name='Имя начальника'),
        ),
    ]
