# Generated by Django 4.2.5 on 2023-10-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0003_alter_reform_boss'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boss',
            table='Boss',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='direction',
            table='Direction',
        ),
        migrations.AlterModelTable(
            name='minister',
            table='Minister',
        ),
        migrations.AlterModelTable(
            name='reform',
            table='Reform',
        ),
    ]
